---
title: "CatData"
author: "Jason Pekos"
date: "10/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# EDA

```{r}
library(tidyverse)
library(ggthemes)
library(ggmap)
library(move)
library(moveVis)
library(cowplot)

CatDatAus = move("PetCatsAus.csv")  #Import Cat Data
CatDatNZ = move("PetCatsNZ.csv")  #Import Cat Data
CatDatUK = move("PetCatsUK.csv")  #Import Cat Data
CatDatUS = move("PetCatsUS.csv")  #Import Cat Data



CatDFAus<-(left_join(as.data.frame(CatDatAus), RefAus, by=c("trackId"="animal.id"))
           %>% mutate(Country = "Australia")
)

CatDFUK<-(left_join(as.data.frame(CatDatUK), RefUK, by=c("trackId"="animal.id"))
 %>% mutate(Country = "United Kingdom")
)
CatDFUS<-(left_join(as.data.frame(CatDatUS), RefUS, by=c("trackId"="animal.id"))
 %>% mutate(Country = "United States")
)
CatDFNZ<-(left_join(as.data.frame(CatDatNZ), RefNZ, by=c("trackId"="animal.id"))
 %>% mutate(Country = "New Zealand")
)

```

```{r}
cats<-union_all(CatDFAus, CatDFNZ)
cats<-union_all(cats, CatDFUK)
cats<-union_all(cats, CatDFUS)

cats <- cats %>% mutate(Country = factor(Country, levels = c("Australia", "New Zealand", "United Kingdom", "United States"))) %>%  arrange(desc(Country))

# AusTest = ggplot(data = CatDFAus, aes(x = timestamp, y = individual.local.identifier)) + geom_line() +
#   theme_tufte() +
#   ggtitle("When are Certain Cats Tracked: Australia?") +
#   labs(x = "Date", y = "Individual Cat") +
#   theme(axis.ticks.y = element_blank(), 
#         axis.text.y  = element_blank())
# 
# NZTest = ggplot(data = CatDFNZ, aes(x = timestamp, y = individual.local.identifier)) + geom_line() +
#   theme_tufte() +
#   ggtitle("When are Certain Cats Tracked: New Zealand") +
#   labs(x = "Date", y = "Individual Cat") +
#   theme(axis.ticks.y = element_blank(), 
#         axis.text.y  = element_blank())
# 
# 
# UKTest = ggplot(data = CatDFUK, aes(x = timestamp, y = individual.local.identifier)) + geom_line() +
#          theme_tufte() +
#          ggtitle("When are Certain Cats Tracked: United Kingdown") +
#          labs(x = "Date", y = "Individual Cat") +
#          theme(axis.ticks.y = element_blank(), 
#          axis.text.y  = element_blank())

FullPlot = ggplot() +
           geom_line(data = cats, aes(x = timestamp, y = individual.local.identifier, color = Country)) +     
           theme_tufte() +
           ggtitle("When are Certain Cats Tracked: Worldwide") +
           labs(x = "Date", y = "Individual Cat Recorded") +
          theme(axis.ticks.y = element_blank(), 
                axis.text.y  = element_blank(),
                axis.ticks.x  = element_blank(),
                axis.text.x  = element_blank(),
                axis.title.x = element_blank(),
                legend.position=c(0.2,0.2)  ) 

DensityPlot = ggplot() +
              geom_density(data = cats, aes(x = timestamp, y = after_stat(count),
                                            color = Country, fill = Country),
                                            inherit.aes = FALSE)  +
              theme_tufte() +
              theme(axis.ticks.y = element_blank(), 
              axis.text.y  = element_blank(),
              legend.title = element_blank(),
              legend.position = "none") +
              labs( y = "Density")

P1 = plot_grid(FullPlot, DensityPlot, rel_heights = c(2, 0.7), ncol = 1 ,nrow = 2, align = "v")

P1
```




```{r}

USPLOT = ggplot(data = CatDFUS, aes(x = timestamp, y = individual.local.identifier)) + geom_line() +
  theme_tufte() +
  ggtitle("When are Certain Cats Tracked: United States") +
  labs(x = "Date", y = "Individual Cat") +
  
  geom_line(data =  CatDFUS %>% filter(individual.local.identifier == "Kagin2" ), aes(color = "Kagin 2"))+
  geom_line(data =  CatDFUS %>% filter(individual.local.identifier == "Lacey" ), aes(color = "Lacey"))+
  geom_line(data =  CatDFUS %>% filter(individual.local.identifier == "Oscar.L" ), aes(color = "Oscar L."))+

  theme(axis.ticks.y = element_blank(), 
        axis.text.y  = element_blank(),
        axis.ticks.x  = element_blank(),
        axis.text.x  = element_blank(),
        axis.title.x = element_blank(),
        legend.position=c(.9,0.2))  + 
  
        scale_colour_manual("", 
                            breaks = c("Kagin 2", "Lacey", "Oscar L."),
                            values = c("blue", "red", "green") )


DensityPlot = ggplot() +
    geom_density(data = CatDFUS, aes(x = timestamp, y = after_stat(count)), inherit.aes = FALSE)  +
    theme_bw() +
    theme(axis.ticks.y = element_blank(), 
          axis.text.y  = element_blank(),
          legend.title = element_blank(),
          legend.position = "none") +
  labs( y = "Density")

P2 = plot_grid(USPLOT, DensityPlot, rel_heights = c(2, 0.7), ncol = 1 ,nrow = 2, align = "v")

P2
```





## Isolate a smaller timeframe to see all the cat labels.

```{r}
CatDFUK %>% filter(timestamps < "2017-09-30" ) %>% filter(timestamps > "2017-09-20")  ->CDFUK2

UKPLOT = ggplot(data = CDFUK2, aes(x = timestamp, y = individual.local.identifier)) + geom_line() +
                theme_bw() +
                ggtitle("When are Certain Cats Tracked: United Kingdown, Truncated") +
                labs(x = "Date", y = "Individual Cat") +
                theme(axis.ticks.y = element_blank(), 
                      axis.text.y  = element_blank(),
                      axis.ticks.x  = element_blank(),
                      axis.text.x  = element_blank(),
                      axis.title.x = element_blank())   

DensityPlot = ggplot() +
    geom_density(data = CDFUK2, aes(x = timestamp, y = after_stat(count)), inherit.aes = FALSE)  +
    theme_bw() +
    theme(axis.ticks.y = element_blank(), 
          axis.text.y  = element_blank(),
          legend.title = element_blank(),
          legend.position = "none") +
  labs( y = "Density")

P3 = plot_grid(UKPLOT, DensityPlot, rel_heights = c(2, 0.7), ncol = 1 ,nrow = 2, align = "v")

P3
##Kagin2
```

```{r}
##Save files:
ggsave("CatTrackTime1.png", P1, width=6.5,height=4)
ggsave("CatTrackTime2.png", P2, width=6.5,height=4)
ggsave("CatTrackTime3.png", P3, width=6.5,height=4)



```

